version: '3.9'
services:
  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  backend:
    image: scheduler-backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports: 
      - 3000:8080
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      NODE_ENV: development