version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6

workflows:
  heroku-deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
jobs:
  build:
    docker:
      - image: cimg/node:18.2.0
      - image: cimg/postgres:14.2
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: schedule-maker-test

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run: yarn test
      - run:
          name: end to end test
          command: yarn test:e2e
          environment:
            DATABASE_URL: postgres://postgres:postgres@localhost:5432/schedule-maker-test
